language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - wget https://github.com/FriendsOfPHP/pickle/releases/download/v0.4.0/pickle.phar
  - php pickle.phar install xdebug
  - php -v
  - composer install

script:
  - vendor/bin/atoum --test-ext
